  <wxappid>${appid}</wxappid>
  <msgappid>${msgappid}</msgappid>
  <send_name>${sendName}</send_name>
  <re_openid>${reOpenid}</re_openid>
  <total_amount>${totalAmount}</total_amount>
  <total_num>${totalNo}</total_num>
  <wishing>${wishing}</wishing>
  <client_ip>${clientIp}</client_ip>
  <act_name>${actName}</act_name>
  <remark>${remark}</remark>
  <scene_id>${sceneId}</scene_id>
  <risk_info>${riskInfo}</risk_info>
  <consume_mch_id>${consumeMchId}</consume_mch_id>