<merNo>${merNo!""}</merNo>
<secMerNo>${secMerNo!""}</secMerNo>
<orderStat>${orderStat!""}</orderStat>
<curr>${curr!""}</curr>
<orderDes>${orderDes!""}</orderDes>
<outerOrderNo>${outerOrderNo!""}</outerOrderNo>
<orderNo>${orderNo!""}</orderNo>
<transAmt>${transAmt!""}</transAmt>
<payServicType>${payServicType!""}</payServicType>
<merDate>${merDate!""}</merDate>
<outerOrderStartDate>${outerOrderStartDate!""}</outerOrderStartDate>
<outerOrderEndDate>${outerOrderEndDate!""}</outerOrderEndDate>
<orderDate>${orderDate!""}</orderDate>
<orderTime>${orderTime!""}</orderTime>
<spbillCreateIp>${spbillCreateIp!""}</spbillCreateIp>
<notifyUrl>${notifyUrl!""}</notifyUrl>
<transComments>${transComments!""}</transComments>
<payTime>${payTime!""}</payTime>
<merFeeAmt>${merFeeAmt!""}</merFeeAmt>