<returnCode>${returnCode!""}</returnCode>
<returnMsg>${returnMsg!""}</returnMsg>
<outerOrderNo>${outerOrderNo!""}</outerOrderNo>
<orderNo>${orderNo!""}</orderNo>
<subOpenid>${subOpenid!""}</subOpenid>
<subIsSubscribe>${subIsSubscribe!""}</subIsSubscribe>
<subAppid>${subAppid!""}</subAppid>
<transAmt>${transAmt!""}</transAmt>
<bankType>${bankType!""}</bankType>
<timeEnd>${timeEnd!""}</timeEnd>
<tradeState>${tradeState!""}</tradeState>
<merFeeAmt>${merFeeAmt!""}</merFeeAmt>