<transStat>${orderStat!""}</transStat>
<refundStatus>${refundStat!""}</refundStatus>
<clearState></clearState>
<payServicType>${payServicType!""}</payServicType>
<transType>${transType!""}</transType>
<bankTransno></bankTransno>
<transAmt>${transAmt!""}</transAmt>
<CURR>${curr!""}</CURR>
<outerOrderNo>${outerOrderNo!""}</outerOrderNo>
<outRefundNo>${oriOrderNo!""}</outRefundNo>
<orderNo>${orderNo!""}</orderNo>
<isSplit>${stlFlag!""}</isSplit>
<timeEnd>${payTime!""}</timeEnd>
<transportFee>${otherTranAmt!""}</transportFee>
<platCharge>${feeAmt!""}</platCharge>
<productFee>${productAmt!""}</productFee>
<attach>${attach!""}</attach>