<returnCode>${returnCode!""}</returnCode>
<returnMsg>${returnMsg!""}</returnMsg>
<outerOrderNo>${outerOrderNo!""}</outerOrderNo>
<orderNo>${orderNo!""}</orderNo>
<subOpenid>${subOpenid!""}</subOpenid>
<subAppid>${subAppid!""}</subAppid>
<transAmt>${transAmt!""}</transAmt>
<prepayId>${prepayId!""}</prepayId>
<paySign>${paySign!""}</paySign>
<timeStamp>${timeStamp!""}</timeStamp>
<nonceStr>${nonceStr!""}</nonceStr>
<tradeType>${tradeType!""}</tradeType>
<merFeeAmt>${merFeeAmt!""}</merFeeAmt>
<signType>${signType!""}</signType>