<orderNo>${orderNo}</orderNo>
<oriOrderNo>${oriOrderNo}</oriOrderNo>
<outerOrderNo>${outerOrderNo}</outerOrderNo>
<outerRefundNo>${outerRefundNo}</outerRefundNo>
<subAppId>${subAppId}</subAppId>
<refundAmt>${transAmt}</refundAmt>
<refundStat>${refundStat}</refundStat>
<orderAmt>${oriTransAmt}</orderAmt>
<CURR>${oriCcy}</CURR>