    <bankCardNo>${bankCardNo}</bankCardNo>
    <currency>${currency}</currency>
    <charge>${charge!""}</charge>
    <set_account>${setAccount!""}</set_account>
    <org_biz_date>${orgBizDate!""}</org_biz_date>
    <org_biz_serialno>${orgBizSerialNo!""}</org_biz_serialno>
    <cvv2>${cvv2!""}</cvv2>
    <validate>${validate!""}</validate>   
    <trantype>${trantype}</trantype>
    <amount>${amount}</amount>
    <third_flag>${thirdFlag}</third_flag>
	<third_account>${thirdAccount}</third_account>
	<third_name>${accountName}</third_name>
	<memocode>${memoCode}</memocode>
