    <accountName>${accountName}</accountName>
    <CVV2>${CVV2}</CVV2>
    <EXPIRE_DATE>${EXPIREDATE}</EXPIRE_DATE>
    <bankCardNo>${bankCardNo}</bankCardNo>
    <certType>${certType}</certType>
    <certNo>${certNo}</certNo>
    <mobilePhone>${mobilePhone}</mobilePhone>
    <isCheckmobilePhone>${isCheckmobilePhone}</isCheckmobilePhone>   
    <isCheckAccountName>${isCheckAccountName}</isCheckAccountName>
    <isCheckCertificateNo>${isCheckCertificateNo}</isCheckCertificateNo>