"body" : {
		 "ROWS":[
        <#list feeGetList as item>
         <#if !item_has_next>
         {			
         		  "FEE_ID":"${item.feeId}",
         		  "FEE_METHOD_NAME":"${item.feeMethodName}",
         		  "FEE_NAME":"${item.feeName}",
         		  "MER_NAME":"${item.merName}",
                  "ACCT_TYPE":"${item.acctType}",
                  "CHNL_ID":"${item.chnId}",
                  "MER_NO":"${item.merNo}",
                  "SEC_MER_NO":"${item.secMerNo}",
                  "TRANS_CODE":"${item.txnCode}",
                  "FEE_CODE":"${item.feeCode}",
                  "ASS_CODE":"${item.assCode}",
                  "START_DATE":"${item.startDate}",
                  "END_DATE":"${item.endDate}",
                  "FREE_CYCLE":"${item.freeCycle}",
                  "FREE_COUNT":"${item.freeCount}",
                  "PER_FEE":"${item.perFee}",
                  "GET_TYPE":"${item.getType}",
                  "LAST_UPD_USER_ID":"${item.lastUpdUserId}",
                  "LAST_UPDATE_TIME":"${item.lastUpdateTime}",
                  "MEMO":"${item.memo}",
                  "DATE_STATE":"${item.dateState}",
                  "ROUTE_CODE":"${item.routeCode}"
         }
          <#else>
                 {
                  "FEE_ID":"${item.feeId}",
         		  "FEE_METHOD_NAME":"${item.feeMethodName}",
                  "FEE_NAME":"${item.feeName}",
                  "MER_NAME":"${item.merName}",
                  "ACCT_TYPE":"${item.acctType}",
                  "CHNL_ID":"${item.chlId}",
                  "MER_NO":"${item.merNo}",
                  "SEC_MER_NO":"${item.secMerNo}",
                  "TRANS_CODE":"${item.txnCode}",
                  "FEE_CODE":"${item.feeCode}",
                  "ASS_CODE":"${item.assCode}",
                  "START_DATE":"${item.startDate}",
                  "END_DATE":"${item.endDate}",
                  "FREE_CYCLE":"${item.freeCycle}",
                  "FREE_COUNT":"${item.freeCount}",
                  "PER_FEE":"${item.perFee}",
                  "GET_TYPE":"${item.getType}",
                  "LAST_UPD_USER_ID":"${item.lastUpdUserId}",
                  "LAST_UPDATE_TIME":"${item.lastUpdateTime}",
                  "MEMO":"${item.memo}",
                  "DATE_STATE":"${item.dateState}",
                  "ROUTE_CODE":"${item.routeCode}"
                 },
                 </#if>
              </#list>
               ]
		}