"body" : {
       "paySign":"${paySign}",
       "nonce_str":"${nonceStr}",
       "mch_id":"${mchId}",
       "timeStamp":"${timeStamp}",
       "out_trade_no":"${outTradeNo}",
       "result_code":"${resultCode}",
       "return_code":"${returnCode}",
       "return_msg":"${returnMsg}",
       "is_subscribe":"${isSubscribe}",
       "bank_type":"${bankType}",
       "trans_amt":"${transAmt}",
       "is_subscribe":"${isSubscribe}",
       "sub_openid":"${subOpenid}",
       "sub_is_subscribe":"${subIsSubscribe}",
       "coupon_fee":"${couponFee}",
       "time_end":"${timeEnd}",
       "openid":"${openid}"
}